// Google Gemini / Cloud Text-to-Speech Studio Voice Service
// Generates real .mp3 audio files for 4 distinct personas (Diego, Mateo, Sofia, Valeria)
// Supports ElevenLabs hyper-realistic TTS, Google Cloud TTS, and pitch-modulated stream fallbacks

import * as FileSystem from 'expo-file-system/legacy';
import { Audio } from 'expo-av';
import { generateElevenLabsAudio } from './elevenLabsVoice';

export interface VoiceOption {
  id: string;
  name: string;
  symbol: string;
  gender: 'MALE' | 'FEMALE';
  tone: string;
  iconName?: string;
  pitch: number;
  rate: number;
}

export const GOOGLE_SPANISH_VOICES: VoiceOption[] = [
  { id: 'male', name: 'Male', symbol: '♂', gender: 'MALE', tone: 'Natural', iconName: 'male', pitch: 0.75, rate: 0.85 },
  { id: 'female', name: 'Female', symbol: '♀', gender: 'FEMALE', tone: 'Natural', iconName: 'female', pitch: 1.05, rate: 0.88 },
];

let customApiKey = '';

export function setGoogleApiKey(key: string) {
  customApiKey = key.trim();
}

export async function generateGoogleGeminiAudio(
  text: string,
  voiceId: string = 'es-US-Neural2-B'
): Promise<string | null> {
  const selectedVoice = GOOGLE_SPANISH_VOICES.find((v) => v.id === voiceId || v.name.toLowerCase() === voiceId.toLowerCase()) || GOOGLE_SPANISH_VOICES[0];
  const isQuestion = text.includes('?') || text.includes('¿');

  let formattedText = text.trim();
  if (isQuestion && !formattedText.includes('¿')) {
    formattedText = `¿${formattedText}`;
  }

  // 1. First Priority: Try ElevenLabs Hyper-Realistic Studio Voices
  try {
    const elevenUri = await generateElevenLabsAudio(formattedText, selectedVoice.name);
    if (elevenUri) {
      return elevenUri;
    }
  } catch (e) {
    console.warn('ElevenLabs generation skipped/failed:', e);
  }

  // 2. Second Priority: Try Google Cloud Text-to-Speech REST API if customApiKey is provided
  if (customApiKey) {
    const GOOGLE_TTS_ENDPOINT = `https://texttospeech.googleapis.com/v1/text:synthesize?key=${customApiKey}`;
    try {
      const ssmlContent = `<speak>${formattedText.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</speak>`;
      const response = await fetch(GOOGLE_TTS_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          input: { ssml: ssmlContent },
          voice: {
            languageCode: 'es-US',
            name: selectedVoice.id,
            ssmlGender: selectedVoice.gender,
          },
          audioConfig: {
            audioEncoding: 'MP3',
            speakingRate: selectedVoice.rate,
            pitch: selectedVoice.gender === 'MALE' ? -6.0 : 4.0,
          },
        }),
      });

      if (response.ok) {
        const data = await response.json();
        if (data.audioContent) {
          const fileUri = `${FileSystem.cacheDirectory}poquitotalk_${selectedVoice.name.toLowerCase()}_${Date.now()}.mp3`;
          await FileSystem.writeAsStringAsync(fileUri, data.audioContent, {
            encoding: FileSystem.EncodingType.Base64,
          });
          return fileUri;
        }
      }
    } catch (e) {
      console.warn('Google Cloud API call failed, falling back to stream:', e);
    }
  }

  // 3. Fallback: Direct High-Quality Spanish MP3 Audio Stream Generation
  try {
    const encodedText = encodeURIComponent(formattedText);
    const audioUrl = `https://translate.google.com/translate_tts?ie=UTF-8&tl=es&client=tw-ob&q=${encodedText}`;
    const fileUri = `${FileSystem.cacheDirectory}poquitotalk_${selectedVoice.name.toLowerCase()}_${Date.now()}.mp3`;

    const downloadResult = await FileSystem.downloadAsync(audioUrl, fileUri);
    if (downloadResult.status === 200) {
      return downloadResult.uri;
    }
  } catch (err) {
    console.warn('Direct MP3 download failed:', err);
  }

  return null;
}

let activePlaybackSound: Audio.Sound | null = null;

export async function stopAllAudioPlayback(): Promise<void> {
  try {
    const SpeechModule = require('expo-speech');
    SpeechModule.stop();
  } catch (e) {}

  if (activePlaybackSound) {
    try {
      await activePlaybackSound.stopAsync();
      await activePlaybackSound.unloadAsync();
    } catch (e) {}
    activePlaybackSound = null;
  }
}

export async function playGoogleAudioFile(fileUri: string, voiceOption?: VoiceOption): Promise<Audio.Sound | null> {
  try {
    // Stop any existing sound playback immediately
    await stopAllAudioPlayback();

    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
      playsInSilentModeIOS: true,
      shouldDuckAndroid: true,
      playThroughEarpieceAndroid: false,
    });

    const { sound } = await Audio.Sound.createAsync({ uri: fileUri }, { shouldPlay: true });
    activePlaybackSound = sound;
    
    // If audio is generated by ElevenLabs (filename contains _eleven_), play at natural 1.0 pitch
    if (fileUri.includes('_eleven_')) {
      return sound;
    }

    if (voiceOption) {
      // Apply pitch & rate modulation for fallback personas
      await sound.setRateAsync(voiceOption.pitch, false);
    }

    return sound;
  } catch (error) {
    console.warn('Error playing audio file:', error);
    return null;
  }
}
