#!/usr/bin/env python3
"""
Bundle the preset voice clips into the app so presets work offline from the very first launch.

Source of truth: assets/audio/presets/{diego,sofia}_{id}.mp3 (re-voice there, then re-run this script).
Output:
  assets/audio/offline/{diego,sofia}_{id}.mp3   speech-optimised copies (mono, 64 kbps)
  src/services/bundledPresetAudio.ts             static require() map Metro can bundle

Only clips the app can actually request are bundled: every phrase id in src/services/presets.ts
(after PRESET_AUDIO_ALIASES) plus every id in src/services/presetTextMap.json.

Usage: python3 scripts/build_offline_presets.py
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets/audio/presets"
OUT = ROOT / "assets/audio/offline"
TS = ROOT / "src/services/bundledPresetAudio.ts"
PERSONAS = ("diego", "sofia")


def needed_ids():
    presets = (ROOT / "src/services/presets.ts").read_text()
    phrase_ids = set(re.findall(r"\{\s*id: '([a-z0-9_]+)',\s*subCategory", presets))
    audio_src = (ROOT / "src/services/presetAudio.ts").read_text()
    alias_block = audio_src.split("PRESET_AUDIO_ALIASES")[1].split("};")[0]
    aliases = dict(re.findall(r"(\w+): '(\w+)'", alias_block))
    text_map_ids = set(json.loads((ROOT / "src/services/presetTextMap.json").read_text()).values())
    # the app applies aliases after resolving an id from either source
    return {aliases.get(i, i) for i in phrase_ids | text_map_ids}


def main():
    ids = sorted(needed_ids())
    shutil.rmtree(OUT, ignore_errors=True)
    OUT.mkdir(parents=True)
    entries, missing = [], []
    for pid in ids:
        for persona in PERSONAS:
            src = SRC / f"{persona}_{pid}.mp3"
            if not src.exists():
                missing.append(src.name)
                continue
            dst = OUT / src.name
            subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", str(src), "-ac", "1", "-ar", "44100",
                            "-b:a", "64k", "-map_metadata", "-1", str(dst)], check=True)
            entries.append(src.stem)

    lines = [
        "// AUTO-GENERATED by scripts/build_offline_presets.py — do not edit by hand.",
        "// Preset voice clips shipped inside the app so they play offline from the first launch.",
        "export const BUNDLED_PRESET_AUDIO: Record<string, number> = {",
        *[f"  '{e}': require('../../assets/audio/offline/{e}.mp3')," for e in entries],
        "};",
        "",
    ]
    TS.write_text("\n".join(lines))

    size = sum(f.stat().st_size for f in OUT.iterdir()) / 1e6
    src_size = sum((SRC / f"{e}.mp3").stat().st_size for e in entries) / 1e6
    print(f"bundled {len(entries)} clips ({len(ids)} phrases x {len(PERSONAS)} voices): "
          f"{src_size:.1f} MB -> {size:.1f} MB")
    if missing:
        print(f"MISSING {len(missing)} source clips: {', '.join(missing)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
